### ISSUE TITLE
"Variable CR is not defined" error when using the plugin with Kitty

### ISSUE THREAD

**Issue by jclsn** [jasonccox/vim-wayland-clipboard#11]
I need the clipboard function for the [scrollback buffer functionality of Kitty](https://sw.kovidgoyal.net/kitty/overview/#the-scrollback-buffer). This works well with X11, but when I am trying to use your plugin, I get the above error.

The plugin works well without Kitty, so I guess it has something to do with the way I open vim. I use the following parameters to open vim in Kitty:

```bash
vim --not-a-term -u ~/.vim/kitty_scrollback.vim +"terminal ++curwin tail -n 10000 "<(tail -n 10000 | sed -e "s/$\x1b'']8;;file:[^\]*[\]//g" ) +"KittyScrollback INPUT_LINE_NUMBER CURSOR_LINE CURSOR_COLUMN"
```

Pretty messy command, I know. The kitty scrollback and all the plugins and theming for the scrollback buffer are provided by this script

```vim
vim9script

set encoding=utf-8

call plug#begin('~/.vim/plugged')
Plug 'jasonccox/vim-wayland-clipboard'
call plug#end()

set clipboard=unnamedplus
set termwinscroll=10000

command -bar -nargs=+ KittyScrollback KittyScrollback(<f-args>)

def KittyScrollback(topline: string, curline: string, curcol: string)
	# preserve cursor position
	var input_line_nr = str2nr(topline)
	var cursor_line = str2nr(curline)
	var cursor_column = str2nr(curcol)
	var last_line = line('$')
	sleep 100m
	call cursor(max([0, input_line_nr - 1]) + cursor_line, cursor_column)
enddef
```

I needed to add your plugin as well. When I try to open the scrollback buffer though, vim tells me "variable CR is not defined" and points me to [this line](https://github.com/jasonccox/vim-wayland-clipboard/blob/9b6def0924e716fb5314d52e062965b950b707f8/plugin/wayland_clipboard.vim#L66).

Any idea why this happens? I tried playing around a bit, but had no success.

**Comment by jasonccox** [comment]
A little online searching suggests that [it could be related to compatible or cpoptions](https://superuser.com/questions/624732/cr-not-recognized-as-variable-in-vim-vimrc-using-putty) -- have you tried that out?

If so, can you reduce this down to a more minimal example? Does it still happen without the spaceduck plugin and without all of the options you're setting? Does it always happen when reading from stdin? The current setup is rather complex to debug.

**Comment by jclsn** [comment]
> A little online searching suggests that [it could be related to compatible or cpoptions](https://superuser.com/questions/624732/cr-not-recognized-as-variable-in-vim-vimrc-using-putty) -- have you tried that out?

Just tried that. Doesn't change anything unfortunately.

I will reduce the example. Actually just the KittyScrollback function is needed.

**Comment by jasonccox** [comment]
I've tried a few things. First, I moved my normal `~/.vim` directory, created a new one, installed vim-plug, and then used vim-plug to install this plugin. `~/.vim` now looks like this:

```
/home/jason/.vim
├── autoload
│   └── plug.vim
└── plugged
    └── vim-wayland-clipboard
        ├── CHANGELOG.md
        ├── LICENSE
        ├── plugin
        │   └── wayland_clipboard.vim
        └── README.md
```

Then I ran put the following in `test-vimrc` and ran `vim -u test-vimrc`:

```
vim9script

call plug#begin('~/.vim/plugged')
Plug 'jasonccox/vim-wayland-clipboard'
call plug#end()
```

This reproduces your issue. Switching to normal vimscript by eliminating the `vim9script` still reproduces. Including `set nocompatible` on the second line of `test-vimrc` doesn't help. However, if I convert to normal vimscript *and* add `set nocompatible` at the beginning of `test-vimrc`, the issue goes away.

I suspect that `set nocompatible` somehow doesn't work in vim9script (I haven't used it much yet). If you make your `kitty_scrollback.vim` file use normal vimscript and include `set nocompatible` at the top, does that fix your issue? Or what about just putting `set nocompatible` at the top of the `wayland_clipboard.vim` file provided by this plugin?

**Comment by jclsn** [comment]
Well, it indeed works when I make your suggested settings and convert the script to legacy vimscript again. The unnamedplus register doesn't work it seems, but when I press ``"*y`` it works now. Guess I can make a remap here.

Thank you for looking into this!
