### ISSUE TITLE
How do I make it yank to system clipboard by default?

### ISSUE THREAD

**Issue by xorbuht** [jasonccox/vim-wayland-clipboard#13]
It works correctly when I e.g. copy a line: "+yy
Then I can successfully paste into other applications.
However I want to copy with just yy, without having to specify the + buffer every time. How do I achieve that?
I've tried adding to my .vimrc file: ":set clipboard=unnamedplus". My understanding is that it should use the "+" buffer by default when I do that. However it does not work.

**Comment by jasonccox** [comment]
That behavior wasn't implemented yet. The `unnamedplus` branch in #14 should do it -- can you try that out for me?

**Comment by xorbuht** [comment]
I have switched to this branch and now it works! 
I have also changed plugin code to call "wl-copy --primary", so now it works exactly as I want - I can paste with middle click.
Thank you for swift help!

**Comment by jasonccox** [comment]
I merged that branch, so you should be able to go back to `master` now. I also added a new commit to master that lets you pass extra arguments to `wl-copy` and `wl-paste`. That should let you pass `--primary` without modifying the script. It's documented in the [README](https://github.com/jasonccox/vim-wayland-clipboard#passing-extra-arguments-to-wl-copy-or-wl-paste).
